/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intelegente_vente;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pc
 */
public final class CLIENT extends javax.swing.JPanel {
Connection conn,conn2;

 PreparedStatement pst;
   ResultSet rs;
    /**
     * Creates new form ProduitT
     */
    public CLIENT() {
        initComponents();
        
          
         
                  Font font = UIManager.getFont("TableHeader.font");
font = font.deriveFont(24f);
UIManager.put("TableHeader.font", font);
    CLIENT();    
    CREDIT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = jTable1 = new javax.swing.JTable(){     public boolean isCellEditable(int rowIndex, int colIndex) {         return false;     } };
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_credit = new javax.swing.JTable();
        jRadio_payement = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        pnl_credit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Combo_categorie = new javax.swing.JComboBox<>();
        txt_crdit = new javax.swing.JTextField();
        payement = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        خروج = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("قائمة الزبائن", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_id.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.setToolTipText("");
        txt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_id.setEnabled(false);
        txt_id.setFocusAccelerator('*');
        txt_id.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_idCaretUpdate(evt);
            }
        });
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("الرقم:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("اللقب");

        txt_nom.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("رقم الهاتف");

        txt_tel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("الاسم");

        txt_prenom.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenomActionPerformed(evt);
            }
        });
        txt_prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_prenomKeyTyped(evt);
            }
        });

        Table_credit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Table_credit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_credit.setGridColor(new java.awt.Color(0, 204, 255));
        Table_credit.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Table_credit.setSelectionForeground(new java.awt.Color(102, 255, 255));
        Table_credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_creditMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_credit);

        buttonGroup1.add(jRadio_payement);
        jRadio_payement.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadio_payement.setText("دفع ديون");
        jRadio_payement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_payementActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jRadioButton2.setText("تسجيل زبون جديد");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        pnl_credit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("المبلغ:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("النوع:");

        Combo_categorie.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Combo_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "دفع ديون", "زيادة ديون" }));
        Combo_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_categorieActionPerformed(evt);
            }
        });

        txt_crdit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_crdit.setToolTipText("");
        txt_crdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_crdit.setFocusAccelerator('*');
        txt_crdit.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_crditCaretUpdate(evt);
            }
        });
        txt_crdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_creditLayout = new javax.swing.GroupLayout(pnl_credit);
        pnl_credit.setLayout(pnl_creditLayout);
        pnl_creditLayout.setHorizontalGroup(
            pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_creditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_crdit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Combo_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        pnl_creditLayout.setVerticalGroup(
            pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_creditLayout.createSequentialGroup()
                .addGroup(pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Combo_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_crdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        payement.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        payement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/ordering.png"))); // NOI18N
        payement.setText("تسديد الدين");
        payement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(payement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(307, 307, 307))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRadio_payement, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnl_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_payement)
                            .addComponent(jRadioButton2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl_credit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payement)
                        .addGap(27, 27, 27))))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/Save-icon.png"))); // NOI18N
        btn_save.setText("حفظ");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/update.png"))); // NOI18N
        btn_update.setText("تغيير");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/eliminar.png"))); // NOI18N
        jButton5.setText("حذف");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/Cancelar.png"))); // NOI18N
        jButton6.setText("الغاء");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        خروج.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        خروج.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/close-icon.png"))); // NOI18N
        خروج.setText("خروج");
        خروج.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                خروجActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/Agregar.png"))); // NOI18N
        jButton2.setText("جديد");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(خروج, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(خروج, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 745, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("التعديل على الزبون و تسيير الديون", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("قائمة الزبائن");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_idCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idCaretUpdate

    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_nomKeyTyped

    private void Combo_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_categorieActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
         conn= MysqlConnect.ConnectDB();
        String sql = "INSERT   INTO  CLIENT ( NOM, PRENOM ,TEL  ) VALUES(?,?,?)" ;

        try {

           
            // create a connection to the database
          
            pst = conn.prepareStatement(sql);
              
           
            pst.setString(1, txt_nom.getText());
            pst.setString(2, txt_prenom.getText());
             pst.setString(3, txt_tel.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
CLIENT();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
      
update();
  JOptionPane.showMessageDialog(null, "تمت  حفظ التغييرات");
  CLIENT();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        this.btn_save.setEnabled(false);
        this.jButton2.setEnabled(true);
        this.btn_update.setEnabled(false);
        this.jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void خروجActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_خروجActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_خروجActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.btn_save.setEnabled(true);
        this.jButton2.setEnabled(false);
        this.btn_update.setEnabled(false);
        this.jButton5.setEnabled(false);
        txt_nom.setText("");
       
         txt_id.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       selectrow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telKeyTyped

    private void txt_prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_prenomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomKeyTyped

    private void Table_creditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_creditMouseClicked
       

       
    }//GEN-LAST:event_Table_creditMouseClicked

    private void txt_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomActionPerformed

    private void txt_crditCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_crditCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crditCaretUpdate

    private void txt_crditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crditActionPerformed

    private void jRadio_payementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_payementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_payementActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void payementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementActionPerformed
     payement_credit(); 
     //insertcredit();
    }//GEN-LAST:event_payementActionPerformed
double t;
int k;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo_categorie;
    private javax.swing.JTable Table_credit;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadio_payement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton payement;
    private javax.swing.JPanel pnl_credit;
    private javax.swing.JTextField txt_crdit;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JButton خروج;
    // End of variables declaration//GEN-END:variables
 void selectrow(){
       javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        //ahora obtenemos la fila selccionada
        int index = jTable1.getSelectedRow();

        if(index<0){
            // no se puede eliminar
            JOptionPane.showMessageDialog(this,"حدد السطر");
          
                    }else {
         
      txt_id.setText(model.getValueAt(index, 3).toString());
        txt_nom.setText(model.getValueAt(index, 2).toString());
        txt_prenom.setText(model.getValueAt(index, 1).toString());
         txt_tel.setText(model.getValueAt(index, 0).toString());
       k=Integer.parseInt(model.getValueAt(index, 3).toString());
 CREDIT();
       jTabbedPane1.setSelectedIndex(1);
     
        
        }
        
        
 }
     void CLIENT(){
      conn2= MysqlConnect.ConnectDB();               
try{
            String sql2 = " SELECT   TEL AS 'رقم الهاتف' , PRENOM  AS 'الاسم', NOM  AS 'اللقب',ID_CLIENT  AS 'رقم الزبون' FROM CLIENT  ";
           

            
            pst= conn2.prepareStatement(sql2);
        rs = pst.executeQuery();

            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {

                if (conn2 != null) {
                    conn2.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

      }

 }      
    void update(){
        
        String sql = "UPDATE CLIENT SET NOM = ? ,PRENOM = ? ,TEL = ? WHERE ID_CLIENT = ? " ;
conn= MysqlConnect.ConnectDB();      
        try {

            
            pst = conn.prepareStatement(sql);
            
            
            pst.setString(1, txt_nom.getText());
            pst.setString(2, txt_prenom.getText());
             pst.setString(3, txt_tel.getText());
             pst.setInt(4, Integer.parseInt(txt_id.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }
    final void CREDIT(){
                    
try{
            String sql2 = "  SELECT PRIX_TOTAL AS 'الباقي'  , PRIX AS 'القيمة الحالية' , GENRE_CREDIT AS 'النوع' , DATE AS 'التاريخ'  ,ID_CREDIT AS 'الرقم' FROM CREDIT where ID_CLIENT='"+k+"' ";
           
conn2= MysqlConnect.ConnectDB();      
            
            pst= conn2.prepareStatement(sql2);
        rs = pst.executeQuery();

            
            Table_credit.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {

                if (conn2 != null) {
                    conn2.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

      }
    }
  void payement_credit(){
    if(jRadio_payement.isSelected()){
       txt_crdit.setEnabled(true);
        if(Combo_categorie.getSelectedItem().equals("دفع ديون") ){
       Connection conn3 = MysqlConnect.ConnectDB();
            try {
            String sql2 = "   select  PRIX_TOTAL from CREDIT where ID_CLIENT='"+k+"' order by  ID_CREDIT DESC LIMIT 1";
           
          PreparedStatement  pst3 = conn3.prepareStatement(sql2);
            //Bind values into the parameters.
           ResultSet rs3 = pst3.executeQuery();
            if(rs3.next()){
             t=Double.parseDouble (rs3.getString(1));  
             INTERFACE i=new INTERFACE();
      String sql4 = "INSERT INTO  CREDIT (  GENRE_CREDIT, DATE, PRIX, PRIX_TOTAL, ID_CLIENT) VALUES(?,?,?,?,?)";
     
      try {
            
            // create a connection to the database
          PreparedStatement  pst7 = conn3.prepareStatement(sql4);
            pst7.setString(1, Combo_categorie.getSelectedItem().toString());
            pst7.setString(2, i.lbl_date.getText());
            pst7.setString(3, txt_crdit.getText());
            double p=Double.parseDouble(txt_crdit.getText());
            pst7.setString(4, String.valueOf((t-p)));
            pst7.setInt(5, Integer.valueOf(txt_id.getText()));

            pst7.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn3 != null) {
                    conn3.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
 
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn3 != null) {
                    conn3.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }   
        
        
        
        } else {
            
        }
    }  
  }
  void insertcredit(){
        INTERFACE i=new INTERFACE();
      String sql4 = "INSERT INTO  CREDIT (  GENRE_CREDIT, DATE, PRIX, PRIX_TOTAL, ID_CLIENT) VALUES(?,?,?,?,?)";
       Connection conn7 = MysqlConnect.ConnectDB();
      try {
            
            // create a connection to the database
          PreparedStatement  pst7 = conn7.prepareStatement(sql4);
            pst7.setString(1, Combo_categorie.getSelectedItem().toString());
            pst7.setString(2, i.lbl_date.getText());
            pst7.setString(3, txt_crdit.getText());
            double p=Double.parseDouble(txt_crdit.getText());
            pst7.setString(4, String.valueOf((t-p)));
            pst7.setInt(5, Integer.valueOf(txt_id.getText()));

            pst7.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn7 != null) {
                    conn7.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
  }
}
