/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package intelegente_vente;

import java.awt.Event;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pc
 */
public class VENTE extends javax.swing.JPanel {

    Connection conn, conn1, conn2, conn3, conn4, conn5, conn6, conn7, conn8, conn9, conn10;
    PreparedStatement pst, pst1, pst2, pst3, pst4, pst5, pst6, pst7, pst8, pst9, pst10;
    ResultSet rs1, rs2, rs3, rs4, rs5, rs6, rs7, rs8, rs9;
    DecimalFormat df = new DecimalFormat("#,##0.00");
    INTERFACE i = new INTERFACE();
    CAISSE c = new CAISSE();

    /**
     * Creates new form VENTE
     */
    public VENTE() {
        initComponents();

        table_commande.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (jCheckBox1.isSelected()) {
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_commande.getModel();
                    //ahora obtenemos la fila selccionada
                    int fila_select = table_commande.getSelectedRow();

                    if (fila_select < 0) {
                        // no se puede eliminar
                        JOptionPane.showMessageDialog(null, "حدد اسم الزبون ");

                    } else {

                        int index = table_commande.getSelectedRow();
                        lbl_nom.setText(model.getValueAt(index, 2).toString());
                        lbl_prenom.setText(model.getValueAt(index, 1).toString());
                        P_credit.setVisible(true);
                        id = Integer.parseInt(model.getValueAt(index, 3).toString());
                        conn = MysqlConnect.ConnectDB();
                       credit();
                    } } else {
                    //   P_credit.setVisible(false);
                    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) table_commande.getModel();
                    //ahora obtenemos la fila selccionada
                    int fila_select = table_commande.getSelectedRow();

                    if (fila_select < 0) {
                        // no se puede eliminar
                        JOptionPane.showMessageDialog(null, "حدد السلعة التي تريداضافتها ");

                    } else {

                        int index = table_commande.getSelectedRow();
                        txt_nom.setText(model.getValueAt(index, 3).toString());
                        txt_prix.setText(model.getValueAt(index, 2).toString());
                        Spin_qty.setValue(1);

                    }

                }
            }

        });
        Font font = UIManager.getFont("TableHeader.font");
        font = font.deriveFont(24f);
        UIManager.put("TableHeader.font", font);

        update_table();
        btn_memeprix.setVisible(false);
        btn_2000da.setVisible(false);
        btn_1000da.setVisible(false);
        btn_500da.setVisible(false);
        tbn_200da.setVisible(false);
        P_credit.setVisible(false);

    }

    private void update_table() {

        try {

            String sql = "select DATE_PERIM AS 'تاريخ انتهاء الصلاحية', QTE_IN_STOCK AS 'الكمية المتوفرة',  PRIX_VENTE AS 'سعر البيع',LABEL_PRODUIT AS 'تسمية السلعة',ID_PRODUIT AS 'رقم السلعة' from PRODUIT";
            conn1 = MysqlConnect.ConnectDB();
            pst1 = conn1.prepareStatement(sql);
            rs1 = pst1.executeQuery();
            table_commande.setModel(DbUtils.resultSetToTableModel(rs1));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {

            } catch (Exception e) {
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_commande = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_Produit = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_payer = new javax.swing.JButton();
        btn_memeprix = new javax.swing.JButton();
        btn_2000da = new javax.swing.JButton();
        btn_1000da = new javax.swing.JButton();
        tbn_200da = new javax.swing.JButton();
        btn_500da = new javax.swing.JButton();
        lbl_reste = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        P_credit = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_nom = new javax.swing.JLabel();
        lbl_prenom = new javax.swing.JLabel();
        lbl_credit_recent = new javax.swing.JLabel();
        lbl_crdit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txt_nom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_prix = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Spin_qty = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1368, 489));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table_commande.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        table_commande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_commande.setGridColor(new java.awt.Color(0, 204, 255));
        table_commande.setSelectionBackground(new java.awt.Color(102, 102, 102));
        table_commande.setSelectionForeground(new java.awt.Color(102, 255, 255));
        table_commande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_commandeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_commande);

        Table_Produit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Table_Produit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المجموع", "العدد", "اسم السلعة"
            }
        ));
        Table_Produit.setGridColor(new java.awt.Color(0, 204, 255));
        Table_Produit.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Table_Produit.setSelectionForeground(new java.awt.Color(102, 255, 255));
        Table_Produit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ProduitMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table_Produit);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/new-icon.png"))); // NOI18N
        jButton1.setText("اضافة طلب");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/delete.png"))); // NOI18N
        jButton2.setText("حذف طلب");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/clear.png"))); // NOI18N
        jButton3.setText("مسح الكل");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_payer.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_payer.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Intelegente_Vente\\src\\intelegente_vente\\Main menu images\\invoice-icon.png")); // NOI18N
        btn_payer.setText("دفع الحساب");
        btn_payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payerActionPerformed(evt);
            }
        });

        btn_memeprix.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_memeprix.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\Intelegente_Vente\\src\\intelegente_vente\\Main menu images\\Calculator-icon (1).png")); // NOI18N
        btn_memeprix.setText("نفس المبلغ");
        btn_memeprix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_memeprixActionPerformed(evt);
            }
        });

        btn_2000da.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_2000da.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/2000DZD.jpg"))); // NOI18N
        btn_2000da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2000daActionPerformed(evt);
            }
        });

        btn_1000da.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_1000da.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/500da-1.jpg"))); // NOI18N
        btn_1000da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1000daActionPerformed(evt);
            }
        });

        tbn_200da.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tbn_200da.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/200da.jpg"))); // NOI18N
        tbn_200da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_200daActionPerformed(evt);
            }
        });

        btn_500da.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_500da.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intelegente_vente/images/Algeria1000Dinar-2005.JPG"))); // NOI18N
        btn_500da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_500daActionPerformed(evt);
            }
        });

        lbl_reste.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        lbl_reste.setForeground(new java.awt.Color(0, 204, 204));
        lbl_reste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_reste.setText("0.00");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("الباقي:");

        jCheckBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jCheckBox1.setText("كريدي");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_reste)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_1000da, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_2000da, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_500da, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbn_200da, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))))
                    .addComponent(btn_memeprix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_payer, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_reste, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btn_memeprix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, 0)
                                .addComponent(jButton3)
                                .addGap(0, 0, 0)
                                .addComponent(btn_payer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_1000da, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_500da, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbn_200da, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_2000da, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        P_credit.setBackground(new java.awt.Color(255, 255, 255));
        P_credit.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("الاسم:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("اللقب:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("ديون سابقة:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("مبلغ الدين:");

        lbl_nom.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_prenom.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_prenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_credit_recent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_credit_recent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbl_crdit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_crdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout P_creditLayout = new javax.swing.GroupLayout(P_credit);
        P_credit.setLayout(P_creditLayout);
        P_creditLayout.setHorizontalGroup(
            P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_creditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lbl_prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_crdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_credit_recent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(P_creditLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(140, 140, 140))
        );
        P_creditLayout.setVerticalGroup(
            P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_creditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_creditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_crdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(P_creditLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_credit_recent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_creditLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("المجموع:");

        Total.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 204, 204));
        Total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Total.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("دج");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_nom.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel16.setText("العدد");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("اسم السلعة");

        txt_prix.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_prix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        txt_prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prixActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("الثمن");

        Spin_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Spin_qty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("بحث");

        jTextField3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Spin_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(27, 27, 27))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Spin_qty, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_prix)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField3))
                        .addGap(1, 1, 1)))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(310, 310, 310)
                        .addComponent(P_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P_credit, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_commandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_commandeMouseClicked


    }//GEN-LAST:event_table_commandeMouseClicked

    private void Table_ProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ProduitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Table_ProduitMouseClicked

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void txt_prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prixActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int c = Integer.parseInt(Spin_qty.getValue().toString());
        double pn = Double.parseDouble(txt_prix.getText());
        somme = c * pn;
        subtot += somme;
        DefaultTableModel model = (DefaultTableModel) Table_Produit.getModel();
        model.addRow(new Object[]{String.valueOf(somme), Spin_qty.getValue().toString(), txt_nom.getText()});

        Total.setText(df.format(subtot));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) Table_Produit.getModel();
        //ahora obtenemos la fila selccionada
        int fila_select = Table_Produit.getSelectedRow();

        if (fila_select < 0) {
            // no se puede eliminar
            JOptionPane.showMessageDialog(this, "حددالطلب التي تريد حذفها");

        } else {

            subtot = subtot - (Double.parseDouble(modelo.getValueAt(fila_select, 0).toString()));
            Total.setText(String.valueOf((double) Math.round(subtot * 100) / 100));

            //  Label_SOMME.setText(""+sub+"دج");
            //   Label_SOMMETOTAL.setText(""+sub+"دج");
            modelo.removeRow(fila_select);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ((DefaultTableModel) table_commande.getModel()).setNumRows(0);
        Total.setText("0.00");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_payerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payerActionPerformed
        if (jCheckBox1.isSelected()) {
           lbl_crdit.setText(String.valueOf(subtot));
            update1();
            insertvente();
            idvente();
            insertventedetail();
            insertcredit();

        } else {

            btn_memeprix.setVisible(true);
            btn_1000da.setVisible(true);
            btn_2000da.setVisible(true);
            btn_500da.setVisible(true);
            tbn_200da.setVisible(true);
            //inserttable();
            update1();
            insertvente1();
            idvente();
            insertventedetail();
            insertcaisse();
        }
    }//GEN-LAST:event_btn_payerActionPerformed

    private void btn_memeprixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_memeprixActionPerformed
        lbl_reste.setText("");
        Total.setText("");
    }//GEN-LAST:event_btn_memeprixActionPerformed

    private void btn_2000daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2000daActionPerformed
        double m = 2000.00;
        m = m - subtot;
        lbl_reste.setText(String.valueOf((double) Math.round(m * 100) / 100));
        Total.setText("");
    }//GEN-LAST:event_btn_2000daActionPerformed

    private void btn_1000daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1000daActionPerformed
        double m = 1000.00;
        m = m - subtot;
        lbl_reste.setText(String.valueOf((double) Math.round(m * 100) / 100));
        Total.setText("");
    }//GEN-LAST:event_btn_1000daActionPerformed

    private void tbn_200daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_200daActionPerformed
        double m = 200.00;
        m = m - subtot;
        lbl_reste.setText(String.valueOf((double) Math.round(m * 100) / 100));
        Total.setText("");
    }//GEN-LAST:event_tbn_200daActionPerformed

    private void btn_500daActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_500daActionPerformed
        double m = 500.00;
        m = m - subtot;
        lbl_reste.setText(String.valueOf((double) Math.round(m * 100) / 100));
        Total.setText("");
    }//GEN-LAST:event_btn_500daActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {

            CLIENT();
            
            jPanel10.setVisible(false);
        } else {
            P_credit.setVisible(false);
            update_table();
            jPanel10.setVisible(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    double subtot;
    public String name;
    double somme = 0.00;
    int id, qty, qty2, qty3;
    int id_vente;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_credit;
    private javax.swing.JSpinner Spin_qty;
    private javax.swing.JTable Table_Produit;
    private javax.swing.JLabel Total;
    private javax.swing.JButton btn_1000da;
    private javax.swing.JButton btn_2000da;
    private javax.swing.JButton btn_500da;
    private javax.swing.JButton btn_memeprix;
    public javax.swing.JButton btn_payer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_crdit;
    private javax.swing.JLabel lbl_credit_recent;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_prenom;
    private javax.swing.JLabel lbl_reste;
    private javax.swing.JTable table_commande;
    private javax.swing.JButton tbn_200da;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prix;
    // End of variables declaration//GEN-END:variables
  void CLIENT() {

        try {
            String sql2 = " SELECT   TEL AS 'رقم الهاتف' , PRENOM  AS 'الاسم', NOM  AS 'اللقب',ID_CLIENT  AS 'رقم الزبون' FROM CLIENT ";
            conn2 = MysqlConnect.ConnectDB();
            pst2 = conn2.prepareStatement(sql2);
            rs2 = pst2.executeQuery();

            table_commande.setModel(DbUtils.resultSetToTableModel(rs2));

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                pst2.close();
                rs2.close();
                if (conn2 != null) {
                    conn2.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }

    }
void credit(){
  try {
            String sql2 = "   select  PRIX_TOTAL from CREDIT where ID_CLIENT='"+id+"' order by  ID_CREDIT DESC LIMIT 1";
            conn3 = MysqlConnect.ConnectDB();
            pst3 = conn3.prepareStatement(sql2);
            //Bind values into the parameters.
            rs3 = pst3.executeQuery();
            if(rs3.next()){
              lbl_credit_recent.setText(rs3.getString(1));  
            }else{
              lbl_credit_recent.setText("0.00");  
              lbl_crdit.setText( String.valueOf(subtot));
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                pst3.close();
                rs3.close();
                if (conn3 != null) {
                    conn3.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }   
}
    final void idvente() {

        try {
            String sql2 = "   select  ID_VENTE from VENTE  order by  ID_VENTE DESC LIMIT 1";
            conn3 = MysqlConnect.ConnectDB();
            pst3 = conn3.prepareStatement(sql2);
            //Bind values into the parameters.
            rs3 = pst3.executeQuery();
            id_vente = rs3.getInt(1);

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                pst3.close();
                rs3.close();
                if (conn3 != null) {
                    conn3.close();

                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }

        }
    }

    /*  void inserttable() {
        
        String sql3 = "SELECT NOM FROM TTABLE WHERE NOM=('" + name + "')";
        try {

           
            // create a connection to the database
            
     pst = conn.prepareStatement(sql3);
          rs = pst.executeQuery();
            if (!rs.next()) {
                String sql2 = "INSERT INTO TTABLE ( NOM ) VALUES(?)";
                try {

                   
                    // create a connection to the database
                    
    pst = conn.prepareStatement(sql2);

    pst.setString(1, name);

     pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "تمت الاضافة");

                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                } finally {
                    try {
                        if (conn != null) {
                            conn.close();
                        }
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }*/
    void update1() {

        int i2 = 0;

        javax.swing.table.DefaultTableModel modelo1 = (javax.swing.table.DefaultTableModel) Table_Produit.getModel();

        while (i2 < Table_Produit.getRowCount()) {

            qty = Integer.parseInt(modelo1.getValueAt(i2, 1).toString());

            try {
                String sql1 = "SELECT QTE_IN_STOCK FROM PRODUIT WHERE LABEL_PRODUIT  =( '" + (modelo1.getValueAt(i2, 2)).toString() + "')";
                conn4 = MysqlConnect.ConnectDB();
                // create a connection to the database
                pst4 = conn4.prepareStatement(sql1);
                //Bind values into the parameters.
                rs4 = pst4.executeQuery();

                qty2 = Integer.parseInt(rs4.getString(1));

                qty3 = qty2 - qty;

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    if (conn4 != null) {
                        conn4.close();
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }

            String sql = "UPDATE PRODUIT SET QTE_IN_STOCK = ?  WHERE  LABEL_PRODUIT = ('" + modelo1.getValueAt(i2, 2).toString() + "') ";

            try {
                conn5 = MysqlConnect.ConnectDB();
                // create a connection to the database
                PreparedStatement pst5 = conn5.prepareStatement(sql);
                pst5.setString(1, String.valueOf(qty3));

                pst5.executeUpdate();
                JOptionPane.showMessageDialog(null, "تمت الاضافة");

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn5 != null) {
                        conn5.close();
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }

            i2++;
        }
    }

    void insertcaisse() {

        String sql4 = "INSERT INTO CAISSE ( DATE,DEBUT,TOTAL, GRAND_TOTAL,ID_VENTE) VALUES(?,?,?,?,?)";
        try {
            conn6 = MysqlConnect.ConnectDB();
            // create a connection to the database
            pst6 = conn6.prepareStatement(sql4);
            pst6.setString(1, i.lbl_date.getText());
            pst6.setString(2, c.txt_debut.getText());
            pst6.setString(3, String.valueOf(subtot));
            pst6.setString(4, String.valueOf((Double.parseDouble(c.txt_grandtotal.getText())) + subtot));
            pst6.setInt(5, id_vente);

            pst6.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn6 != null) {
                    conn6.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    void insertcredit() {

        String sql4 = "INSERT INTO  CREDIT (  GENRE_CREDIT, DATE, PRIX, PRIX_TOTAL, ID_CLIENT) VALUES(?,?,?,?,?)";
        try {
            conn7 = MysqlConnect.ConnectDB();
            // create a connection to the database
            pst7 = conn7.prepareStatement(sql4);
            pst7.setString(1, "زيادة ديون");
            pst7.setString(2, i.lbl_date.getText());
            pst7.setString(3, String.valueOf(subtot));
            pst7.setString(4, String.valueOf((Double.parseDouble(lbl_credit_recent.getText()) + subtot)));
            pst7.setInt(5, id);

            pst7.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn7 != null) {
                    conn7.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    void insertvente() {

        String sql4 = "INSERT INTO VENTE (DATE_VENTE,ID_CLIENT) VALUES(?,?)";

        try {
            conn8 = MysqlConnect.ConnectDB();
            // create a connection to the database
            pst8 = conn8.prepareStatement(sql4);

            pst8.setString(1, i.lbl_date.getText().toString());
            pst8.setInt(1, id);

            pst8.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn8 != null) {
                    conn8.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    void insertvente1() {

        String sql4 = "INSERT INTO VENTE (DATE_VENTE) VALUES(?)";

        try {
            conn9 = MysqlConnect.ConnectDB();
            // create a connection to the database
            pst9 = conn9.prepareStatement(sql4);

            pst9.setString(1, i.lbl_date.getText());

            pst9.executeUpdate();
            JOptionPane.showMessageDialog(null, "تمت الاضافة");

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                if (conn9 != null) {
                    conn9.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }

    void insertventedetail() {
        javax.swing.table.DefaultTableModel modelo1 = (javax.swing.table.DefaultTableModel) Table_Produit.getModel();
        int i2 = 0;

        while (i2 < Table_Produit.getRowCount()) {

            String sql4 = "INSERT INTO VENTE_DETAIL ( ID_PRODUIT,ID_VENTE,QTE) VALUES(?,?,?)";
            try {
                conn10 = MysqlConnect.ConnectDB();
                // create a connection to the database
                pst10 = conn10.prepareStatement(sql4);
                pst10.setString(1, (modelo1.getValueAt(i2, 2).toString()));
                pst10.setInt(2, id_vente);
                pst10.setString(3, (modelo1.getValueAt(i2, 1).toString()));

                pst10.executeUpdate();
                JOptionPane.showMessageDialog(null, "تمت الاضافة");

            } catch (SQLException e) {
                System.out.println(e.getMessage());
            } finally {
                try {
                    if (conn10 != null) {
                        conn10.close();
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }
            }
            i2++;
        }

    }

}
